### PR TITLE
Refined custom list usage

### PR DESCRIPTION
**Pull request by chrispiccaro18**

### CODE REVIEW

**Comment by sts10** [comment]
trusting you on these!

**Comment by chrispiccaro18** [comment]
Haha, I’ve been double checking!

Have you tried it?

**Comment by sts10** [comment]
Just with `git pull` and running locally (looks fine). Not testing in/with Docker. But not sweating it.

**Comment by chrispiccaro18** [comment]
Ok. Ya, it doesn’t touch anything local. Lmk if you give it a go with
docker - I think you’d dig it.

**Pull request merged**
